### PR TITLE
Fetch data with the QR Code Scanned

### PR DESCRIPTION
**Pull request by successtar**
This is an additive feature to what is currently available.

The new functionality allow the app to use the Qr Code Scan to fetch data from API endpoint

The API endpoint used is https://qr-scanner-api.herokuapp.com/api/user/{QR_CODE} with the source code available here https://github.com/successtar/qr-scanner-api

When a Qr code is scan the app use the code to fetch the specific user details and display it.

Sample Qr Images are available in Qr_Images directory for testing.

### CODE REVIEW

**Comment by happysingh23828** [comment]
@successtar , please resolve the conflict so I can test and merge your code.

**Comment by happysingh23828** [comment]
Thanks, @successtar , will check

**Comment by successtar** [comment]
Hi @happysingh23828 

What is the update on this?

**Comment by happysingh23828** [comment]
@successtar why this QR API is required to show user details at this repo? We can do the same thing by making the QR code with JSON data and convert those data into POJO. I think the same you are doing with Unique UUID.

can you explain more on this feature?

**Comment by successtar** [comment]
@happysingh23828 The idea is that when you scan a QR code, you get a id or link pointing to a resource on web. So, instead of just displaying the QR Code to the user, you can have a layer feature that use the QR code to fetch data online. 

To demonstrate that, I created the QR API hosted on heroku to see how you can use the QR Code to fetch resource via api. The data is hosted somewhere online, which means the data is dynamic. The record can be changed online without making changes to the app, more QR code can be created and the data for each code added to the api endpoint without making changes to the app instead of building the json data into the app.

**Comment by happysingh23828** [comment]
@successtar  Thanks for the clarification, do you have an endpoint to generate QR code also? Currently, I'm seeing it's incomplete.

**Comment by successtar** [comment]
@happysingh23828 I use this web platform to generate QR Code https://www.the-qrcode-generator.com/

**Comment by successtar** [comment]
@happysingh23828 test QR Codes are in this directory https://github.com/successtar/Qr-Code-Scanner-/tree/master/Qr_Images

**Comment by happysingh23828** [comment]
@successtar got it, but the structure of the QR code you are hardcoding at your endpoint. it is not universal or dynamic. This QR scanner scans any QR code, which cannot be available on your server. 

then why implement it in this? you are storing QR code's responded on your server manually.

**Comment by successtar** [comment]
@happysingh23828 The API End Point is not a full fledged application, it is just to demonstrate what the api end point return and how the app retrieve the data. You can change the endpoint in the app to point to somewhere else. The End Point can be simple or complex application. 

I recently built a demo app for waste management company that I make use of this code, so when the waste collect get to your apartment they scan your QR code then the app use the code to fetch your information on their server which allow them to know if you have paid for the month or not. The response return by their server is just like the response I simulate with the Nodejs code.

**Comment by happysingh23828** [comment]
@successtar  got it, just update the Readme.MD according to you, will merge today itself.

**Comment by successtar** [comment]
@happysingh23828 Kindly check the update

**Comment by happysingh23828** [comment]
Thanks @successtar

**Pull request merged**
